?program: [(state)+]

// statement
?state: expr NEWLINE
      | function
      | assignment NEWLINE
      | return_state NEWLINE
function: "def" new_symbol "(" [parameter ("," parameter)*] ")" "{" program "}"
assignment: new_symbol "=" expr
return_state: "return" expr

// expression
?expr: term
     | addition
     | substraction
     | function_call
addition: expr "+" term
substraction: expr "-" term
function_call: symbol "[" [expr ("," expr)*] "]"

?term: fact
     | multiplication
     | division
multiplication: term "*" fact
division: term "/" fact

?fact: number
     | symbol
     | priority
?priority: "(" expr ")"
symbol: WORD
number: SIGNED_NUMBER

new_symbol: WORD
parameter: WORD

%import common.WORD
%import common.SIGNED_NUMBER
%import common.WS

%import common.WS_INLINE
%import common.NEWLINE

%ignore WS_INLINE
%ignore WS

%ignore /\\\r?\n/   // バックスラッシュ＋改行は継続行
